baseURL = 'https://thebossmagnus.github.io'
languageCode = 'en-us'
title = 'TheBossMagnus site'
theme = "terminal"
paginate = 4

[params]
    themeColor = "red"
    centerTheme = true

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "TheBossMagnus's Website"
    subtitle = ""
    owner = "TheBossMagnus"
    keywords = ["TheBossMagnus"]
    copyright = "© TheBossMagnus 2023"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "TheBossMagnus's Website"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "thunder"
        name = "Thunder"
        url = "/thunder"
